# Generated by Django 4.0.5 on 2022-06-12 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myawwards', '0005_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='content_rate',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='design_rate',
            new_name='design',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='usability_rate',
            new_name='usability',
        ),
    ]
